# Generated by Django 4.0.3 on 2022-04-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='projector',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
