# Generated by Django 4.0.3 on 2022-04-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='id_reservation',
            new_name='id_reserve',
        ),
    ]
